import "reflect-metadata";
import { auth } from "@ai-hackathon/auth";
import { env } from "@ai-hackathon/env/server";
import { NestFactory } from "@nestjs/core";
import swaggerUi from "swagger-ui-express";
import { openApiDocument } from "@ai-hackathon/api";
import { createOpenApiExpressMiddleware } from "trpc-openapi";
import { appRouter } from "@ai-hackathon/api/routers/index";
import { createContext } from "@ai-hackathon/api/context";

import { AppModule } from "./app.module";

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  app.enableCors({
    origin: env.CORS_ORIGIN,
    methods: ["GET", "POST", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization"],
    credentials: true,
  });

  const expressApp = app.getHttpAdapter().getInstance();
  expressApp.all("/api/auth/*path", async (req: any, _res: any) => {
    return auth.handler(req);
  });

  // Expose REST routes natively generated by trpc-openapi
  expressApp.use("/api", createOpenApiExpressMiddleware({ router: appRouter, createContext }));

  // Serve Swagger UI
  expressApp.use("/api/docs", swaggerUi.serve, swaggerUi.setup(openApiDocument));

  await app.listen(3000);
  console.log("Server is running on http://localhost:3000");
}

bootstrap();
